### PR TITLE
formal or informal for german translation

### PR DESCRIPTION
**Pull request by Frxhb**
Hello!
I am also a translator for the Pi-Hole Remote app. In the pihole remote app, the informal form of address ("Du"/"Deine" instead of "Sie"/"Ihre" ) was used for the German language. 
Should this also be done for this app / all other remaining strings? If so, I can gladly change / correct that.

### CODE REVIEW

**Comment by jojost1** [comment]
@Frxhb hmm.. what do you think? I think I prefer a more _informal_ tone, but I guess it can depend on the language itself as well.

**Comment by Frxhb** [comment]
> @Frxhb hmm.. what do you think? I think I prefer a more _informal_ tone, but I guess it can depend on the language itself as well.

I do also prefer the "informal" variant as in pihole remote.
If you allow me, ill change the current formal language to informal.

**Comment by jojost1** [comment]
Sure, informal seems best then :-) thank you! I'll integrate the translations asap when you push them so you can check them in the beta.

**Review by jojost1 — APPROVED** [review]

**Comment by jojost1** [comment]
There are some conflicts, could you fix those? Must be due to new strings or other changes.

**Pull request closed without merging**
