### PR TITLE
Add TR

### PR DESCRIPTION
**Pull request by emrekeles**

### CODE REVIEW

**Review by jojost1 — APPROVED** [review]
Wow, that's great!! I'll integrate them for the next beta build so you can double-check them in the app if you want. @emrekeles what can I note down inside the 'Made by RocketScience' screen as thanks? For other translators it includes name & a url, such as a Twitter, GitHub etc.

**Comment by jojost1** [comment]
Also: I might have added some extra translations since you started translating, I'll double check and add the English resources to the TR file if that's the case.

**Comment by emrekeles** [comment]
> Wow, that's great!! I'll integrate them for the next beta build so you can double-check them in the app if you want. @emrekeles what can I note down inside the 'Made by RocketScience' screen as thanks? For other translators it includes name & a url, such as a Twitter, GitHub etc.

Twitter @emrekeles

**Comment by jojost1** [comment]
Great, I'll add that url! 😄 If you could enable notifications for the repo so you get a notification when there are new resources, that would be great!

**Comment by emrekeles** [comment]
Can you write Emre Keleş as a name?  Link in twitter.com/emrekeles

**Pull request merged**
