### PR TITLE
Adds italian translation

### PR DESCRIPTION
**Pull request by gmcinalli**

### CODE REVIEW

**Review by jojost1 — APPROVED** [review]
Amazing, thanks!

**Comment by jojost1** [comment]
@gmcinalli they'll be included in the next TestFlight beta. Are you already in the beta?

There's one new resource I've added to the Italian file just now that was still missing, it was added after I created the file. The resource is `rocketscience_mango_subtitle`.

Also: what should I put on the 'Made by RocketScience' for you? Can be a (nick)name and optional url (Twitter, Blog, Github, etc)!

**Comment by gmcinalli** [comment]
@jojost1 No, I'm not in the beta, how can I join it?

I will translate the new resource really soon, no worries!

For the "Made by RocketScience" section you can put my full name (Gian Marco Cinalli) and a link to my LinkedIn profile: https://www.linkedin.com/in/gmcinalli/, thank you!

**Comment by jojost1** [comment]
Great, thanks!!

What's your AppleID mail? I'll add you to the beta!

**Comment by gmcinalli** [comment]
@jojost1 How can I monitor any additions of new strings from you?

**Comment by jojost1** [comment]
@gmcinalli you can 'watch' this repository, which will alert (through mail if you want) on any commit from me!

**Pull request merged**
