### PR TITLE
added german translation

### PR DESCRIPTION
**Pull request by Frxhb**
added german translation. 
I did not translate the word "query" and "log" cause I think its like "Client" tech-speech and shouldn't be translated. If I missed a string, tell me ;-)

ps: check your mails ;))

### CODE REVIEW

**Review by jojost1 — APPROVED** [review]

**Comment by jojost1** [comment]
> I did not translate the word "query" and "log" cause I think its like "Client" tech-speech and shouldn't be translated. If I missed a string, tell me ;-)

I agree!

> ps: check your mails ;))

Ah yes, about the support right? Sorry for not replying, I've been busy with v3.0 😄 I think it's possible to add the files here to support German translations. It does mean that when I specifically add an 'announcement' (you might have seen one in February when I was away for a month) it will be English because those announcements are often very time-crucial if you know what I mean.

**Comment by Frxhb** [comment]
> I think it's possible to add the files here to support German translations.

Awesome. Just tell me when its here on GitHub so I can translate them (just if you want ;))

**Comment by jojost1** [comment]
@Frxhb they're available! https://github.com/jojost1/adguardhomeremote-translations/tree/main/Support

I'm also adding you to the TestFlight now so you can check the translations. Thanks!

**Comment by Frxhb** [comment]
> they're available! https://github.com/jojost1/adguardhomeremote-translations/tree/main/Support

almost finished.... ;)

**Pull request merged**
