### PR TITLE
Update zh-Hant

### PR DESCRIPTION
**Pull request by lancelot-moon**
add the app there??? Weird.

### CODE REVIEW

**Review by jojost1 — APPROVED** [review]
Yeah bit strange, feel free to translate into something more logical for your language if you'd like ;-)

**Comment by lancelot-moon** [comment]
@jojost1 
Is the language selection the same with what is in  iOS setting?
Or provide macOS example.
Thanks.

**Comment by jojost1** [comment]
@lancelot-moon here's an example:

image

**Comment by lancelot-moon** [comment]
@jojost1
You don't know my meaning.
Not the screenshot.
I mean to go to system preferences -> language & region -> apps on macOS.
The screenshot of macOS system preferences.
Why should a user add app there?

On iPadOS, users don't need to add app there.
After intalling an app, just find it in the setting and choose a language if wanting to change the app's language.

**Comment by jojost1** [comment]
Ah, like that! It works very differently on macOS:

image

image

image

**Comment by lancelot-moon** [comment]
@jojost1 
Yes, they're very different between macOS and iOS.
Thanks.

**Pull request merged**
